config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'pages#home'

  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                              :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :services

  resources :services do
    resources :orders, only: [:create]
  end

  resources :services do
    resources :reviews, only: [:create, :destroy]
  end

  resources :charges
  resources :orders, only: [:show]

  get '/user_orders'=> 'orders#user_orders'
  get '/user_sales'=> 'orders#user_sales'

  get '/search', to: 'search#search'
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

  validates :quantity, presence: true
  validates :price, presence: true
  validates :total_price, presence: true
  validates :service_id, presence: true

  before_save :set_order_price

  private
    def set_order_price
      self.total_price = self.quantity * self.price
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :service
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base

	belongs_to :user
	has_many :orders
	has_many :reviews


	has_attached_file :image, styles: { medium: "300x300>", small:"230x140>", thumb: "100x100>" }

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :title, presence: true, length: {maximum:80}
	validates :description, presence: true, length: {maximum:1200}
	validates :price, presence: true
	validates :delivery_time, presence: false
	validates :revisions, presence: false
	validates :requirement, presence: true, length: {maximum:450}

	def average_rating
		reviews.count == 0 ? 0 :reviews.average(:star).round(2)
	end

	def self.search(query)
		where("title LIKE ? OR description LIKE ? OR requirement LIKE ?",
		 "%#{query}", "%#{query}", "%#{query}")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  validates:fullname, presence:true ,length:{maximum: 50}
  validates:description, presence:false ,length:{maximum: 1500}

  has_many :services
  has_many :orders
  has_many :reviews


  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.fullname = auth.info.name
        user.description = auth.info.description
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :email, :description, :password])

    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => params[:total_price],
      :description => params[:description],
      :currency    => 'usd'
    )

    service = Service.find(params[:service_id])

    order = Order.create(
      user: current_user,
      service: service,
      service_id: params[:service_id],
      stripe_email: params[:stripeEmail],
      price: params[:price],
      total_price: params[:total_price],
      quantity: params[:quantity],
      description: charge.description,
      currency: charge.currency,
      stripe_customer_id: customer.id )

    redirect_to user_orders_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to_new_user_registration_url
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def user_orders
    @orders = current_user.orders
  end

  def user_sales
    @services = current_user.services
  end

 private
 def order_params
   params.require(:order).permit(:quantity, :price, :total_price, :service_id)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'landing'

  def home
    @service = Service.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = current_user.reviews.create(review_params)
    redirect_to @review.service
  end

  def destroy
    @review = Review.find(params[:id])
    service = @review.service
    @review.destroy

    redirect_to service
  end

  private
    def review_params
      params.require(:review).permit(:comment, :star, :service_id)
    end
  end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @services = Service.all.order("created_at DESC")
  end

  def search
    if params[:q]
      @services = Service.search(params[:q]).order("created_at DESC")
    else
      @services = Service.all.order("created_at DESC")
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @services = current_user.services
  end

  def show
    @is_buyer = Order.where("service_id = ? AND user_id = ?", @service.id, current_user.id).present? if current_user

    @reviews = @service.reviews
    @reviewed = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(service_params)

    if @service.save
      redirect_to @service
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
    else
      render :edit
    end
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:title, :description, :price, :requirements, :image, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase

      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixerr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>

<%= yield %>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixerr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <!-- <%= form_for([@service, @service.orders.new]) do |f| %>
      <%= f.hidden_field :service_id, value: @service.id %>
      <%= f.hidden_field :price, value: @service.price  %> -->
    <!-- <center>
      <%= f.submit "Order Now ($#{@service.price})", class: "btn btn-primary btn-lg btn-order"%>
    </center> -->
    <center>
      <%= form_tag charges_path, id:'chargeForm' do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js"></script>
        <%= hidden_field_tag 'stripeToken' %>
        <%= hidden_field_tag 'stripeEmail' %>
        <%= hidden_field_tag 'price', @service.price %>
        <%= hidden_field_tag 'total_price', {id:"total_price"} %>
        <%= hidden_field_tag 'service_id', @service.id %>
        <%= hidden_field_tag 'description', @service.title %>

        <button id="btn-order" class="btn btn-primary btn-lg btn-order" type="button">
           Order Now ($<%= @service.price %>)
        </button>

        <script>
          var handler = StripeCheckout.configure({
            key: '<%= Rails.configuration.stripe[:publishable_key] %>',
            token: function(token, arg) {
              document.getElementById("stripeToken").value = token.id;
              document.getElementById("stripeEmail").value = token.email;
              document.getElementById("chargeForm").submit();
            }
          });

          document.getElementById('btn-order').addEventListener('click', function(e){
            var quantity = $('#quantity').val();
            var total_price = (quantity * "<%= @service.price %>") + "00";
            $('#total_price').val(total_price);
            handler.open({
              name: "Sixerr",
              description: "<%= @service.title %>",
              amount: total_price
            });
            e.preventDefault();
          });
        </script>
         <!-- class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount="500"
                data-locale="auto"></script> -->
      <!-- <% end %> -->
    </center>
    <hr>
    <h5 class="pull-left">Basic Gig Quantity</h5>
    <div class="form-group pull-right">
      <div class="select-control">
        <%= select_tag(:quantity, options_for_select([["1 ($#{@service.price * 1})", 1],
        ["2 ($#{@service.price * 2})", 2], ["3 ($#{@service.price * 3})", 3],
        ["4 ($#{@service.price * 4})", 4], ["5 ($#{@service.price * 5})", 5]]), {id: "quantity"}) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
     $("select").bind("change",function() {
       $('.btn-order').html('Order Now - ' + $("select option:selected").html());
     });
 })

</script>

app/views/orders/user_orders.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <center>
            <%= image_tag get_avatar_url(current_user), class: "img-circle img-responsive img-seller-avatar" %>
            <h3><%= current_user.fullname %></h3>
        </center>
      </div>
      <div class="panel-body">
		 		<%= current_user.description %>
		 	</div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>My Orders</h3>
      </div>

      <div class="panel-body">
        <% @orders.each do |order| %>
        <div class="row">
          <div class="col-md-2">
          <%= link_to service_path(order.service) do %>
          <%= image_tag order.service.image.url(:thumb) %>
          <% end %>
        </div>

          <div class="col-md-3">
          <%= link_to service_path(order.service) do %>
          <h4><%= order.service.title %></h4>
          <% end %>
        </div>

          <div class="col-md-2">
          <h5>Quantity: <%= order.quantity %>
              Price: $<%= order.price %>
          </h5>
          </div>

          <div class="col-md-2">
            <h5><%= order.created_at.strftime('%b %d, %Y') %></h5>
          </div>

          <div class="col-md-2">
          <h5>
              Total Price: $<%= order.total_price %>
          </h5>
          </div>

          </div>
          <hr>
        <% end %>
      </div>

    </div>
  </div>

  </div>
</div>
</div>

app/views/orders/user_sales.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12">

    <div class="panel panel-default">
      <div class="panel-body">
        <h3>My Sales</h3>
      </div>

      <div class="panel-body">
        <% @services.each do |service| %>
        <% service.orders.each do |order| %>


          <div class="row">
            <div class="col-md-2">
            <%= link_to service_path(order.service) do %>
            <%= image_tag order.service.image.url(:thumb) %>
            <% end %>
          </div>

            <div class="col-md-2">
            <%= link_to service_path(order.service) do %>
            <h4><%= order.service.title %></h4>
            <% end %>
          </div>

            <div class="col-md-2">
            <h5>Quantity: <%= order.quantity %>
                Price: $<%= order.price %>
            </h5>
            </div>

            <div class="col-md-2">
              <span><%= image_tag get_avatar_url(order.user), class:"navbar-avatar img-circle" %></span>
              </span>
              <h5><%= order.user.fullname %></h5>
            </div>

            <div class="col-md-2">
              <h5><%= order.created_at.strftime('%b %d, %Y') %></h5>
            </div>

            <div class="col-md-2">
            <h5>
                Total: $<%= order.total_price %>
            </h5>
            </div>

            </div>
            <hr>
          <% end %>
        <% end %>

      </div>

    </div>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero">
  <div class="container">
    <div class="row">
      <div class="hero-heading">
      What do you need dear?<br>
      Find it here.<br><br><br><br><br>
      <p>I.Could.Be.The.One</p>
    </div>
  </div>

  <%= render 'search/form' %>
  </div>
</div>


<div class="container section">
	<h1>
		Newest Service
	</h1>
	<div class="row">
    <% @service.each do |service| %>
      <div class="col-md-3">
        <%= link_to(service) do %>
        <div class="gig-card">
          <center> <%= image_tag service.image.url(:small) %> </center>
          <h4>
            <%= service.title %>
          </h4>
          <h3>
            <%= service.price %>
          </h3>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Add a Review</h3>
  </div>
  <div class="panel-body">
      <%= form_for([@service, @service.reviews.new]) do |f| %>

        <div id="star-rating"></div><br/>
        <div class="form-group">
          <%= f.text_area :comment, rows:3, class: "form-control" %><br/>
          <%= f.hidden_field :service_id, value: @service.id %>
          <%= f.submit "Add Review", class:"btn pull-right" %>
        </div>
      <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#star-rating').raty({
    path: '/assets',
    scoreName: 'review[star]',
    score: 1
  });
</script>

app/views/reviews/_list.html.erb
<% if @reviews.count == 0 %>
  <div>
    <center><h4>There are no reviews yet.</h4></center>
  </div>
<% else %>
  <% @reviews.order("id desc").each do |r| %>
    <div class="panel-body">
      <div class="col-md-2">
        <%= image_tag get_avatar_url(r.user), class: "img-circle img-responsive img-user-avatar" %>
      </div>
      <div class="col-md-7">
        <p> <strong><%= r.user.fullname %> &nbsp; <span id="stars_<%= r.id %>"></span>
         </strong></p>
        <p> <%= r.comment %></p>
      </div>
      <div class="col-md-3 pull-right">
          <%= r.created_at.strftime('%b %d, %Y')%><br/>
          <%= link_to "Remove my review", [@service, r], method: :delete, data: {confirm: "Are you sure?"} if current_user && current_user == r.user %>
      </div>
    </div>
    <script>
      $('#stars_<%= r.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= r.star %>
      });
    </script>
  <% end %>
<% end %>

app/views/search/_form.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <%= form_tag(search_path, :method => "get", id: "search-form") do %>
      <div class="input-group input-group-lg">
        <%= text_field_tag :q, params[:q], class:"form-control", placeholder: "What are you looking for..." %>
        <span class="input-group-btn">
          <%= submit_tag "Find Services", :name => nil, class:"btn btn-default" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/search/search.html.erb
<div class="container section">

  <h1>Services Search</h1>
  <%= render 'search/form' %>
  <br><br>
  <div class="row">
    <% if @services.blank? %>
      <center>
        <h4>No services found matching <%= params[:q] %>.</h4>
      </center>
    <% end %>
  </div>

  <div class="row">
      <% @services.each do |service| %>
      <div class="col-md-3">
        <%= link_to(service) do %>
        <div class="gig-card">
          <center><%= image_tag service.image.url(:small)%></center>
          <h4>
            <%= service.title %>
          </h4>
          <h3>
            $<%= service.price %>
          </h3>
        </div>
        <% end %>
      </div>
      <% end %>
  </div>

</div>

app/views/services/_form.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2><%=@service.new_record? ? "Create Your Gig" : "Edit Your Gig" %></h2>
    </div>

    <div class="panel-body">
      <%=form_for @service do |f| %>
      <% if @service.errors.any? %>
      <div class="alert alert-info">
        <h3>
							Fix the following <%= pluralize(@service.errors.count, "error") %> before continuing:
						</h3>
						<ul>
							<% @service.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
      </div>
      <% end %>

      <div class="form-group">
        <label> Gig Title</label>
        <%= f.text_area :title, placeholder: "Ex:I'll do it", row:"2", class:"form-control" %>
      </div>

      <div class="form-group">
        <label> Description</label>
        <%= f.text_area :description,  row:"5", class:"form-control" %>
      </div>

        <div class="form-group">
          <label> Pricing</label>
          <div class="select-control">
            <%= f.select :price,  [["$6","6"],["$18","18"],["$24","24"]], class:"form-control" %>
        </div>
      </div>

        <div class="form-group">
          <label> Requirement</label>
          <%= f.text_area :requirement,  row:"5", class:"form-control" %>
        </div>

        <div class="form-group">
          <label>Add Photo</label>
          <%= f.file_field :image %>
        </div>
        <hr>
        <%= f.submit @service.new_record? ? "Publish Gig" : "Update Gig", class:"btn btn-primary" %>
      <% end %>
     </div>
   </div>
 </div>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <center>
              <%= image_tag get_avatar_url(current_user), class: "img-circle img-responsive img-seller-avatar" %>
              <h3><%= current_user.fullname %></h3>
          </center>
        </div>
        <div class="panel-body">
          <%= current_user.description %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3>My Gigs</h3>
        </div>
        <div class="panel-body">
          <% @services.each do |service| %>
            <div class="row">
              <div class="col-md-2">
                <%= image_tag service.image.url(:thumb) %>
              </div>
              <div class="col-md-7">
                <h4><%= service.title %></h4>
              </div>
              <div class="col-md-3">
                <%= link_to "Update", edit_service_path(service), class: "btn btn-default pull-right" %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<br><br>
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3><%= @service.title %></h3>
				</div>
				<div class="panel-body">
				<%= image_tag(@service.image.url, :class => "img-responsive") %>
				</div>

		 		<div class="panel panel-default">
				 <div class="panel-heading">
					<h3>About This Gig</h3>
					</div>
				<div class="panel-body">
					<p><%= @service.description %></p>
				</div>
			</div>

			<%= render 'reviews/form' if @is_buyer && !@reviewed %>
			<div class="panel panel-default">
 		  	<div class="panel-heading">
 		 		 <h3>Reviews</h3>
 			  </div>
				<%= render 'reviews/list' %>
 		 </div>

		</div>
	 </div>

	 <div class="col-md-4">
		 <%= render 'orders/form' %>

		 <div class="panel panel-default">
		 <div class="panel-body">
			 <h5 class="pull-left">
			 	<%= pluralize(@reviews.count, "Reviews from buyers") %>
			</h5>
			<h4 class="pull-right">
				<%= @service.average_rating %>
			</h4>
			<div id="average_rating" class="pull-right image-average-rating-stars"></div>

			 </div>
			</div>

		 <div class="panel panel-default">
		 	<div class="panel-heading">
		 		<center>
		 				<%= image_tag get_avatar_url(current_user), class:"img-circle img-responsive img-seller-avatar" %>
		 				<h3><%= current_user.fullname %></h3>
		 		</center>
		 	</div>
		 	<div class="panel-body">
		 		<%= current_user.description %>
		 	</div>
		 </div>
	 </div>

	</div>
</div>

<script>
	$('#average_rating').raty({
		path: '/assets',
		readOnly: true,
		score: <%= @service.average_rating %>
	});

</script>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Sixerr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(search_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
        <%= text_field_tag :q, params[:q], class:"form-control", placeholder: "Find Services" %>
        <%= submit_tag "Search", :name => nil, class:"btn btn-default" %>
      <% end %>
      <div>

      <ul class="nav navbar-nav navbar-right">
        <% if (user_signed_in?) %>
           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            <span><%= image_tag get_avatar_url(current_user), class:"img-circle navbar-avatar"%></span>
            <%= current_user.fullname %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li class="dropdown-header">Buying</li>
              <li><%= link_to "My Orders", user_orders_path %></li>

              <li class="dropdown-header">Selling</li>
              <li><%= link_to "My Gigs", services_path %></li>
              <li><%= link_to "Create a Gig", new_service_path %></li>
              <li><%= link_to "Manage Sales", user_sales_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Join", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li> <%= link_to "Start Selling", new_user_session_path, class:"btn btn-default navbar-btn" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">

      <div class="panel panel-default">
        <div class="panel-heading">
          <center>
              <%= image_tag get_avatar_url(@user), class: "img-circle img-responsive img-seller-avatar" %>
              <h3><%= @user.fullname %></h3>
            </center>
          </div>

          <div class="panel-body">
            <%= @user.description %>
          </div>
        </div>

      </div>
    </div>
  </div>